### ISSUE TITLE
Handle token expiration

### ISSUE THREAD

**Issue by wfleming** [codeclimate/aws-cloudwatch-statsd-backend#3]
```
May 04 10:54:47 ip-10-20-50-40 statsd:  Flushing metrics at 2017-05-04T14:54:47.000Z
May 04 10:54:47 ip-10-20-50-40 statsd:  { ExpiredToken: The security token included in the request is expired
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.extractError (/root/statsd/node_modules/aws-sdk/lib/protocol/query.js:39:29)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.callListeners (/root/statsd/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.emit (/root/statsd/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.emit (/root/statsd/node_modules/aws-sdk/lib/request.js:604:14)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.transition (/root/statsd/node_modules/aws-sdk/lib/request.js:21:12)
May 04 10:54:47 ip-10-20-50-40 statsd:      at AcceptorStateMachine.runTo (/root/statsd/node_modules/aws-sdk/lib/state_machine.js:14:12)
May 04 10:54:47 ip-10-20-50-40 statsd:      at /root/statsd/node_modules/aws-sdk/lib/state_machine.js:26:10
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.<anonymous> (/root/statsd/node_modules/aws-sdk/lib/request.js:22:9)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.<anonymous> (/root/statsd/node_modules/aws-sdk/lib/request.js:606:12)
May 04 10:54:47 ip-10-20-50-40 statsd:      at Request.callListeners (/root/statsd/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
May 04 10:54:47 ip-10-20-50-40 statsd:    message: 'The security token included in the request is expired',
May 04 10:54:47 ip-10-20-50-40 statsd:    code: 'ExpiredToken',
May 04 10:54:47 ip-10-20-50-40 statsd:    time: 2017-05-04T14:54:47.364Z,
May 04 10:54:47 ip-10-20-50-40 statsd:    statusCode: 403,
May 04 10:54:47 ip-10-20-50-40 statsd:    retryable: true }
```

**Comment by dblandin** [comment]
@wfleming Is this still something we care about?
